homepage/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name='homepage'

urlpatterns = [
	path('', views.home, name='home'),
	path('About/', views.about, name='about'),
	# path('Event/', views.event, name='event'),
	path('Contact/', views.contact, name='contact'),
	path('event/', views.event, name='event'),
	url(r'event/(?P<pk>[0-9]+)/delete/$', views.eventDelete.as_view(), name='eventDelete')
]

story4/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

class savedEvent(models.Model):
	title = models.CharField(max_length=80)
	date = models.DateField()
	time = models.TimeField()
	category = models.CharField(max_length=50)
	notes = models.CharField(max_length=300)

homepage/forms.py
from django import forms
from homepage import models

class DateInput(forms.DateInput):
	input_type = 'date'

class EventForm(forms.Form):
	title = forms.CharField(
			label = 'Title :',
			max_length = 80,
			required = True,
			widget = forms.TextInput(attrs={
									'class' : 'form-control',
									'type' : 'text',
									'placeholder' : "What's up?"})
	)
	date = forms.DateField(
			label = 'Date :',
			required = True,
			widget = forms.DateInput(attrs={
									'class' : 'form-control',
									'type' : 'date'})
	)
	time = forms.TimeField(
        label = 'Time',
        input_formats = ['%H:%M'],
        widget = forms.TextInput(attrs={'class' : 'form-control form-control-sm',
        								'placeholder' : '00:00'})
    )
	category = forms.ChoiceField(
			label = 'Category :',
			required = True,
			choices = [('goal', 'Goal'),
					  ('memo', 'Memo'),
					  ('schedule', 'Schedule'),
					  ('meeting', 'Meeting'),
					  ('hangout', 'Hangout'),
					  ('other', 'Other')],
			widget = forms.Select(attrs={'class' : 'form-control form-control-sm'})
	)
	notes = forms.CharField(
			label = 'Notes :',
			required = False,
			widget = forms.Textarea(attrs={
									'class' : 'form-control',
									'type' : 'text',
									'placeholder' : "Here for some notes / Memo"})
	)

class Meta:
	model = models.savedEvent
	fields = ('title', 'date', 'time', 'category', 'notes')

homepage/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from homepage import forms, models
from .models import savedEvent
from datetime import datetime

class eventDelete(DeleteView):
	model = savedEvent
	success_url = reverse_lazy('homepage:event')

def home(request):
	return render(request, 'Home.html')

def about(request):
	return render(request, 'About.html')

def contact(request):
	return render(request, 'Contact.html')

def event(request):
	if request.method == 'POST':
		print("a")
		form = forms.EventForm(request.POST)

		if 'id' in request.POST:
			savedEvent.objects.get(id=request.POST['id']).delete()
			return redirect('/event/')

		if form.is_valid():
			print("b")
			event = models.savedEvent(
					title = form.data['title'],
					date = form.data['date'],
					time = form.data['time'],
					category = form.data['category'],
					notes = form.data['notes']
			)
			event.save()
			return redirect('/event/')

	else:
		form = forms.EventForm()

	event_content = {	'events_active' : 'active',
						'context' : {'now' : datetime.now()},
						'events' : models.savedEvent.objects.all().values(),
						'form' : form   }
	return render(request, 'event.html', event_content)

homepage/templates/About.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Putsal's Profile</title>
	<meta name="viewport" content="width=device-width, initial scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
	<section class="about">
		<img src="{% static 'images/Free.jpg' %}" class="img_about">
		<svg> <rect></rect> </svg>

		<header class="sectionbar" role="navigation" aria-label="main navigation">
				<ul>					
					<a href="{% url 'homepage:about' %}"><h2>About</h2></a>

					<a href="{% url 'homepage:event' %}"> Event </a>
					
					<a href="{% url 'homepage:contact' %}"> Contact </a>
				</ul>
		</header>

		<div class="about_content">
			<li><img src="{% static 'images/Box 1.png' %}" class="img_box"></li>
			<img src="{% static 'images/Foto Putsal.png' %}" class="img_profile">
			<li><img src="{% static 'images/Box 2.png' %}" class="img_box"></li>
		</div>

		<footer><a href="{% url 'homepage:home' %}">
			<img src="{% static 'images/homebtn.png' %}" class="homebtn">
		</a></footer>
	</section>
</body>

</html>

homepage/templates/Contact.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Putsal's Profile</title>
	<meta name="viewport" content="width=device-width, initial scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
	<section class="contact">
		<img src="{% static 'images/Contact Cropped.png' %}" class="img_contact">
		<svg style="background: rgba(0, 0, 0, 0.55);"> <rect></rect> </svg>

		<header class="sectionbar" role="navigation" aria-label="main navigation">
				<ul>
					<a href="{% url 'homepage:about' %}"> About </a>

					<a href="{% url 'homepage:event' %}"> Event </a>
					
					<a href="{% url 'homepage:contact' %}"><h2>Contact</h2></a>
				</ul>
		</header>

		<div class="contact_png">
			<li><a href=""><img src="{% static 'images/phone.png' %}"></li></a>
			<li><a href=""><img src="{% static 'images/email.png' %}"></li></a>
			<li><a href="line://ti/p/putrisalsa_l"><img src="{% static 'images/line.png' %}"></a></li>
			<li><a href="https://instagram.com/putrisalsa_l"><img src="{% static 'images/instagram.png' %}"></a></li>
		</div>

		<div class="cont_text">
			<li class="text">0812 7976 0029</li>
			<li class="text2">putrisalsa2607@gmail.com</li>
			<li class="text3">putrisalsa_l</li>
			<li class="text3">putrisalsa_l</li>
		</div>

		<footer><a href="{% url 'homepage:home' %}">
			<img src="{% static 'images/homebtn.png' %}" class="homebtn">
		</a></footer>
	</section>
</body>

</html>

homepage/templates/Home.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Putsal's Profile</title>
	<meta name="viewport" content="width=device-width, initial scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
	<section class="homepage">
		<img src="{% static 'images/Cover.jpg' %}" class="img_home">
		<svg> <rect></rect> </svg>

		<header>
			Graphic Design Lover &nbsp; &otimes;  &nbsp; UI/UX Designer Wanna Be
		</header>
		<h1>Putri Salsabila</h1>
		
		<nav class="navbar" role="navigation" aria-label="main navigation">
			<ul style="margin-left: auto; margin-right: auto;">
				<a href="{% url 'homepage:about' %}"> About </a>

				<a href="{% url 'homepage:event' %}"> Event </a>
				
				<a href="{% url 'homepage:contact' %}"> Contact </a>
			</ul>
		</nav>
	</section>
</body>

</html>

homepage/templates/event.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
       
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Event's Putsal</title>
</head>
<body>
	<section class="half container-fluid flex-column flex-lg-row">
		<div class="schedule col-sm h-100 d-flex justify-content-center align-items-center">
			<form method="POST">
				{% csrf_token %}
				{% for field in form %}
				<p class="w-100 justify-content-center my-1">{{ field.label }}: <br> {{ field }}</p>
			    {% endfor %}
			    <button type="submit" value="Submit" class="btn btn-primary mx-auto mt-2">Submit</button>
			</form>
		</div>
	</section>

	<section id="event" class="schedule container-fluid w-100 d-flex flex-column flex-lg-row justify-content-center align-items-center" style="background: #87CEEB;">
		<div class="row bg-white m-auto w-50" style="overflow: hidden; overflow-y:auto; height: 70%;">
			{% for i in events %}
			<div ><h5>Title :</h5></div>
			<div><p>{{ i.title }}</p></div>
			<div><h5>Date :</h5></div>
			<div><p>{{ i.date }}</p></div>
			<div><h5>Time :</h5></div>
		    <div><p>{{ i.time }}</p></div>
		    <div><h5>Category :</h5></div>
		    <div><p>{{ i.category }}</p></div>
		    <div><h5>Notes :</h5></div>
		    <div><p>{{ i.notes }}</p></div>

		    <div class="col-sm-12 d-flex align-items-end justify-content-end">
		        <form method="POST" action="{% url 'homepage:eventDelete' i.id %}">
		          {% csrf_token %}
		          <input name="id" value="{{i.id}}" type="hidden">
		          <button type="" class="btn-sm col-2" style="margin-left: 30%; font-size: 0.8rem;">Delete</button>
		        </form>
		    </div>
		    {% endfor %}
		</div>
	</section>
</body>
</html>